#!/bin/bash
# compile and run 
CURRENT_DIR=`pwd`
source ./setup.sh
make mydict
make 

# total number of events
TotalEvents=10000

# if -1, use CPU seed
UseSeed=-1

./main.exe tev14_SM_A14_NNPDF23LO.py out/out_pythia8_sm14tev.root $TotalEvents $UseSeed
echo "Add is done for out/out_pythia8_sm14tev.root"
