#!/bin/bash
# compile and run 
CURRENT_DIR=`pwd`
source ./setup.sh


# compile 
make mydict
make 

# total number of events
TotalEvents=1000000

# if -1, use CPU seed
UseSeed=-1

./main.exe tev13_SM_A14_NNPDF23LO.py out/out_pythia8_sm13tev.root $TotalEvents $UseSeed
echo "Add is done for out/out_pythia8_sm14tev.root"
