#!/bin/bash
# compile and run 
CURRENT_DIR=`pwd`
source ./setup.sh


# compile 
make mydict
make 

# total number of events
TotalEvents=1000000

# if -1, use CPU seed
UseSeed=-1

OUTPUT="out/out_pythia8_sm14tev.root"

./main.exe tev14_SM_A14_NNPDF23LO.py $OUTPUT  $TotalEvents $UseSeed
echo "Add is done for $OUTPUT"
